### ISSUE TITLE
make & make install not working on ubuntu 11.10 x64

### ISSUE THREAD

**Issue by madmantm** [moxie0/tortunnel#2]
the lib boost libraries are probably too recent.

/Downloads/tortunnel-0.3$ make
g++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tortunnel\" -DVERSION=\"0.3\" -I.    -ggdb -g -O2 -MT TorProxy.o -MD -MP -MF .deps/TorProxy.Tpo -c -o TorProxy.o TorProxy.cpp
In file included from TorTunnel.h:42:0,
                 from TorProxy.h:40,
                 from TorProxy.cpp:30:
protocol/Directory.h:74:3: error: ‘list’ in namespace ‘std’ does not name a type
make: **\* [TorProxy.o] Error 1

thanks for your help!

**Comment by fs111** [comment]
This should be fixed in the latest HEAD here. Can you try to clone this repo and try again?

**Comment by madmantm** [comment]
well when i do the git clone https://github.com/moxie0/tortunnel.git 

i get all the files, but when i come to do the ./configure i get command not found, has the installation changed with the new git version?

thanks again!

**Comment by madmantm** [comment]
madmantm@:~/tortunnel$ ls
AUTHORS       depcomp      missing            ProxyShuffler.h      SocksConnection.h  TorScanner.h
ChangeLog     INSTALL      NEWS               README               TorProxy.cpp       TorTunnel.cpp
configure.ac  install-sh   protocol           ShuffleStream.h      TorProxy.h         TorTunnel.h
COPYING       Makefile.am  ProxyShuffler.cpp  SocksConnection.cpp  TorScanner.cpp     util
madmantm@:~/tortunnel$ cat INSTALL 
To install:

Extract and run: ./configure; make;

To build, you'll need the boost libraries and openssl.
madmantm@:~/tortunnel$

**Comment by fs111** [comment]
welcome to the wonderful world of autofoo :-) tortunnel uses the GNU autotools for generating first a configure and based on that the final Makefile, to build everything. Here is what you have to do:

git clone https://github.com/moxie0/tortunnel.git
cd tortunnel
autoreconf
automake --add-missing
./configure
make

HTH

**Comment by madmantm** [comment]
still doesn't work unfortunately, but thanks for the autofoo tip! 
madmantm@unknown:~$ git clone https://github.com/moxie0/tortunnel.git
Cloning into tortunnel...
remote: Counting objects: 78, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 78 (delta 41), reused 72 (delta 35)
Unpacking objects: 100% (78/78), done.
madmantm@unknown:~$ cd tortunnel/
madmantm@unknown:~/tortunnel$ autoreconf
madmantm@unknown:~/tortunnel$ automake --add-missing
madmantm@unknown:~/tortunnel$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
configure: creating ./config.status
config.status: creating Makefile
config.status: executing depfiles commands
madmantm@unknown:~/tortunnel$ make
g++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tortunnel\" -DVERSION=\"0.3\" -I.    -ggdb -g -O2 -MT TorProxy.o -MD -MP -MF .deps/TorProxy.Tpo -c -o TorProxy.o TorProxy.cpp
mv -f .deps/TorProxy.Tpo .deps/TorProxy.Po
g++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tortunnel\" -DVERSION=\"0.3\" -I.    -ggdb -g -O2 -MT HybridEncryption.o -MD -MP -MF .deps/HybridEncryption.Tpo -c -o HybridEncryption.o `test -f 'protocol/HybridEncryption.cpp' || echo './'`protocol/HybridEncryption.cpp
mv -f .deps/HybridEncryption.Tpo .deps/HybridEncryption.Po
g++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tortunnel\" -DVERSION=\"0.3\" -I.    -ggdb -g -O2 -MT Connection.o -MD -MP -MF .deps/Connection.Tpo -c -o Connection.o `test -f 'protocol/Connection.cpp' || echo './'`protocol/Connection.cpp
mv -f .deps/Connection.Tpo .deps/Connection.Po
g++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tortunnel\" -DVERSION=\"0.3\" -I.    -ggdb -g -O2 -MT Cell.o -MD -MP -MF .deps/Cell.Tpo -c -o Cell.o `test -f 'protocol/Cell.cpp' || echo './'`protocol/Cell.cpp
mv -f .deps/Cell.Tpo .deps/Cell.Po
g++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tortunnel\" -DVERSION=\"0.3\" -I.    -ggdb -g -O2 -MT Directory.o -MD -MP -MF .deps/Directory.Tpo -c -o Directory.o `test -f 'protocol/Directory.cpp' || echo './'`protocol/Directory.cpp
mv -f .deps/Directory.Tpo .deps/Directory.Po
g++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tortunnel\" -DVERSION=\"0.3\" -I.    -ggdb -g -O2 -MT ServerListing.o -MD -MP -MF .deps/ServerListing.Tpo -c -o ServerListing.o `test -f 'protocol/ServerListing.cpp' || echo './'`protocol/ServerListing.cpp
mv -f .deps/ServerListing.Tpo .deps/ServerListing.Po
g++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tortunnel\" -DVERSION=\"0.3\" -I.    -ggdb -g -O2 -MT Util.o -MD -MP -MF .deps/Util.Tpo -c -o Util.o `test -f 'util/Util.cpp' || echo './'`util/Util.cpp
mv -f .deps/Util.Tpo .deps/Util.Po
g++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tortunnel\" -DVERSION=\"0.3\" -I.    -ggdb -g -O2 -MT Circuit.o -MD -MP -MF .deps/Circuit.Tpo -c -o Circuit.o `test -f 'protocol/Circuit.cpp' || echo './'`protocol/Circuit.cpp
mv -f .deps/Circuit.Tpo .deps/Circuit.Po
g++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tortunnel\" -DVERSION=\"0.3\" -I.    -ggdb -g -O2 -MT CellEncrypter.o -MD -MP -MF .deps/CellEncrypter.Tpo -c -o CellEncrypter.o `test -f 'protocol/CellEncrypter.cpp' || echo './'`protocol/CellEncrypter.cpp
mv -f .deps/CellEncrypter.Tpo .deps/CellEncrypter.Po
g++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tortunnel\" -DVERSION=\"0.3\" -I.    -ggdb -g -O2 -MT RelayCellDispatcher.o -MD -MP -MF .deps/RelayCellDispatcher.Tpo -c -o RelayCellDispatcher.o `test -f 'protocol/RelayCellDispatcher.cpp' || echo './'`protocol/RelayCellDispatcher.cpp
mv -f .deps/RelayCellDispatcher.Tpo .deps/RelayCellDispatcher.Po
g++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tortunnel\" -DVERSION=\"0.3\" -I.    -ggdb -g -O2 -MT CellConsumer.o -MD -MP -MF .deps/CellConsumer.Tpo -c -o CellConsumer.o `test -f 'protocol/CellConsumer.cpp' || echo './'`protocol/CellConsumer.cpp
mv -f .deps/CellConsumer.Tpo .deps/CellConsumer.Po
g++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tortunnel\" -DVERSION=\"0.3\" -I.    -ggdb -g -O2 -MT ProxyShuffler.o -MD -MP -MF .deps/ProxyShuffler.Tpo -c -o ProxyShuffler.o ProxyShuffler.cpp
mv -f .deps/ProxyShuffler.Tpo .deps/ProxyShuffler.Po
g++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tortunnel\" -DVERSION=\"0.3\" -I.    -ggdb -g -O2 -MT CreateCell.o -MD -MP -MF .deps/CreateCell.Tpo -c -o CreateCell.o `test -f 'protocol/CreateCell.cpp' || echo './'`protocol/CreateCell.cpp
mv -f .deps/CreateCell.Tpo .deps/CreateCell.Po
g++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tortunnel\" -DVERSION=\"0.3\" -I.    -ggdb -g -O2 -MT CreatedCell.o -MD -MP -MF .deps/CreatedCell.Tpo -c -o CreatedCell.o `test -f 'protocol/CreatedCell.cpp' || echo './'`protocol/CreatedCell.cpp
mv -f .deps/CreatedCell.Tpo .deps/CreatedCell.Po
g++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tortunnel\" -DVERSION=\"0.3\" -I.    -ggdb -g -O2 -MT TorTunnel.o -MD -MP -MF .deps/TorTunnel.Tpo -c -o TorTunnel.o TorTunnel.cpp
mv -f .deps/TorTunnel.Tpo .deps/TorTunnel.Po
g++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tortunnel\" -DVERSION=\"0.3\" -I.    -ggdb -g -O2 -MT SocksConnection.o -MD -MP -MF .deps/SocksConnection.Tpo -c -o SocksConnection.o SocksConnection.cpp
mv -f .deps/SocksConnection.Tpo .deps/SocksConnection.Po
g++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tortunnel\" -DVERSION=\"0.3\" -I.    -ggdb -g -O2 -MT Network.o -MD -MP -MF .deps/Network.Tpo -c -o Network.o `test -f 'util/Network.cpp' || echo './'`util/Network.cpp
mv -f .deps/Network.Tpo .deps/Network.Po
g++ -ggdb -g -O2 -lssl -lboost_system-mt -lcrypto  -o torproxy TorProxy.o HybridEncryption.o Connection.o Cell.o Directory.o ServerListing.o Util.o Circuit.o CellEncrypter.o RelayCellDispatcher.o CellConsumer.o ProxyShuffler.o CreateCell.o CreatedCell.o TorTunnel.o SocksConnection.o Network.o  
TorProxy.o: In function `error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to`boost::system::system_category()'
TorProxy.o: In function `get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to`boost::system::system_category()'
TorProxy.o: In function `error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to`boost::system::system_category()'
/usr/include/boost/system/error_code.hpp:315: undefined reference to `boost::system::system_category()'
TorProxy.o: In function`~posix_tss_ptr':
/usr/include/boost/asio/detail/posix_tss_ptr.hpp:48: undefined reference to `pthread_key_delete'
/usr/include/boost/asio/detail/posix_tss_ptr.hpp:48: undefined reference to`pthread_key_delete'
TorProxy.o: In function `error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to`boost::system::system_category()'
/usr/include/boost/system/error_code.hpp:315: undefined reference to `boost::system::system_category()'
/usr/include/boost/system/error_code.hpp:315: undefined reference to`boost::system::system_category()'
TorProxy.o: In function `get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to`boost::system::system_category()'
TorProxy.o: In function `error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to`boost::system::system_category()'
TorProxy.o:/usr/include/boost/asio/error.hpp:220: more undefined references to `boost::system::system_category()' follow
TorProxy.o: In function`boost::asio::detail::posix_tss_ptr_create(unsigned int&)':
/usr/include/boost/asio/detail/impl/posix_tss_ptr.ipp:34: undefined reference to `pthread_key_create'
TorProxy.o: In function`get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
/usr/include/boost/asio/error.hpp:220: undefined reference to`boost::system::system_category()'
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
/usr/include/boost/asio/error.hpp:220: undefined reference to`boost::system::system_category()'
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
TorProxy.o:/usr/include/boost/asio/error.hpp:220: more undefined references to`boost::system::system_category()' follow
TorProxy.o: In function `boost::asio::detail::posix_tss_ptr<boost::asio::detail::call_stack<boost::asio::detail::task_io_service>::context>::operator boost::asio::detail::call_stack<boost::asio::detail::task_io_service>::context*() const':
/usr/include/boost/asio/detail/posix_tss_ptr.hpp:54: undefined reference to`pthread_getspecific'
TorProxy.o: In function `boost::asio::detail::tss_ptr<boost::asio::detail::call_stack<boost::asio::detail::task_io_service>::context>::operator=(boost::asio::detail::call_stack<boost::asio::detail::task_io_service>::context*)':
/usr/include/boost/asio/detail/posix_tss_ptr.hpp:60: undefined reference to`pthread_setspecific'
TorProxy.o: In function `get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to`boost::system::system_category()'
TorProxy.o: In function `error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to`boost::system::system_category()'
TorProxy.o: In function `boost::asio::detail::posix_tss_ptr<boost::asio::detail::call_stack<boost::asio::detail::task_io_service>::context>::operator=(boost::asio::detail::call_stack<boost::asio::detail::task_io_service>::context*)':
/usr/include/boost/asio/detail/posix_tss_ptr.hpp:60: undefined reference to`pthread_setspecific'
TorProxy.o: In function `error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to`boost::system::system_category()'
TorProxy.o: In function `boost::asio::detail::posix_tss_ptr<boost::asio::detail::call_stack<boost::asio::detail::task_io_service>::context>::operator=(boost::asio::detail::call_stack<boost::asio::detail::task_io_service>::context*)':
/usr/include/boost/asio/detail/posix_tss_ptr.hpp:60: undefined reference to`pthread_setspecific'
TorProxy.o: In function `get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to`boost::system::system_category()'
TorProxy.o: In function `error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to`boost::system::system_category()'
TorProxy.o: In function `__static_initialization_and_destruction_0':
/usr/include/boost/system/error_code.hpp:214: undefined reference to`boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:215: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:216: undefined reference to`boost::system::system_category()'
TorProxy.o: In function `get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to`boost::system::system_category()'
TorProxy.o: In function `error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to`boost::system::system_category()'
TorProxy.o: In function `get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to`boost::system::system_category()'
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
TorProxy.o:/usr/include/boost/asio/error.hpp:220: more undefined references to`boost::system::system_category()' follow
Connection.o: In function `Connection::initializeSSL()':
/home/madmantm/tortunnel/protocol/Connection.cpp:59: undefined reference to`SSL_load_error_strings'
/home/madmantm/tortunnel/protocol/Connection.cpp:60: undefined reference to `SSL_library_init'
/home/madmantm/tortunnel/protocol/Connection.cpp:62: undefined reference to`SSLv23_client_method'
/home/madmantm/tortunnel/protocol/Connection.cpp:62: undefined reference to `SSL_CTX_new'
/home/madmantm/tortunnel/protocol/Connection.cpp:63: undefined reference to`SSL_CTX_set_verify'
/home/madmantm/tortunnel/protocol/Connection.cpp:65: undefined reference to `BIO_s_mem'
/home/madmantm/tortunnel/protocol/Connection.cpp:65: undefined reference to`BIO_new'
/home/madmantm/tortunnel/protocol/Connection.cpp:66: undefined reference to `BIO_s_mem'
/home/madmantm/tortunnel/protocol/Connection.cpp:66: undefined reference to`BIO_new'
/home/madmantm/tortunnel/protocol/Connection.cpp:67: undefined reference to `SSL_new'
/home/madmantm/tortunnel/protocol/Connection.cpp:69: undefined reference to`SSL_set_bio'
Connection.o: In function `error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to`boost::system::system_category()'
Connection.o: In function `get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to`boost::system::system_category()'
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
Connection.o: In function`error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to `boost::system::system_category()'
Connection.o: In function`get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
Connection.o:/usr/include/boost/system/error_code.hpp:315: more undefined references to`boost::system::system_category()' follow
Connection.o: In function `~Connection':
/home/madmantm/tortunnel/protocol/Connection.cpp:403: undefined reference to`SSL_CTX_free'
/home/madmantm/tortunnel/protocol/Connection.cpp:404: undefined reference to `SSL_free'
Connection.o: In function`error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to `boost::system::system_category()'
Connection.o: In function`Connection::readIntoBufferComplete(boost::function<void (boost::system::error_code const&)>, boost::system::error_code const&, unsigned long)':
/home/madmantm/tortunnel/protocol/Connection.cpp:240: undefined reference to `BIO_write'
Connection.o: In function`error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to `boost::system::system_category()'
Connection.o: In function`get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
/usr/include/boost/asio/error.hpp:220: undefined reference to`boost::system::system_category()'
Connection.o: In function `Connection::writeFromBuffer(boost::function<void (boost::system::error_code const&)>)':
/home/madmantm/tortunnel/protocol/Connection.cpp:247: undefined reference to`BIO_ctrl_pending'
/home/madmantm/tortunnel/protocol/Connection.cpp:249: undefined reference to `BIO_read'
Connection.o: In function`error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to `boost::system::system_category()'
Connection.o: In function`reactive_socket_send_op':
/usr/include/boost/system/error_code.hpp:315: undefined reference to `boost::system::system_category()'
Connection.o: In function`Connection::writeFromBuffer(boost::function<void (boost::system::error_code const&)>)':
/home/madmantm/tortunnel/protocol/Connection.cpp:247: undefined reference to `BIO_ctrl_pending'
Connection.o: In function`get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
Connection.o: In function`error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to `boost::system::system_category()'
/usr/include/boost/system/error_code.hpp:315: undefined reference to`boost::system::system_category()'
Connection.o: In function `get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to`boost::system::system_category()'
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
Connection.o:/usr/include/boost/system/error_code.hpp:315: more undefined references to`boost::system::system_category()' follow
Connection.o: In function `Connection::handshake(boost::function<void (boost::system::error_code const&)>, boost::system::error_code const&)':
/home/madmantm/tortunnel/protocol/Connection.cpp:201: undefined reference to`SSL_do_handshake'
/home/madmantm/tortunnel/protocol/Connection.cpp:206: undefined reference to `SSL_get_error'
Connection.o: In function`error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to `boost::system::system_category()'
Connection.o: In function`Connection::renegotiateCiphers(boost::function<void (boost::system::error_code const&)>, boost::system::error_code const&)':
/home/madmantm/tortunnel/protocol/Connection.cpp:189: undefined reference to `SSL_set_cipher_list'
/home/madmantm/tortunnel/protocol/Connection.cpp:190: undefined reference to`SSL_renegotiate'
Connection.o: In function `Connection::writeFully(unsigned char*, int, boost::function<void (boost::system::error_code const&)>, boost::system::error_code const&)':
/home/madmantm/tortunnel/protocol/Connection.cpp:138: undefined reference to`SSL_write'
/home/madmantm/tortunnel/protocol/Connection.cpp:140: undefined reference to `SSL_get_error'
Connection.o: In function`error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to `boost::system::system_category()'
/usr/include/boost/system/error_code.hpp:315: undefined reference to`boost::system::system_category()'
Connection.o: In function `get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to`boost::system::system_category()'
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
Connection.o: In function`error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to `boost::system::system_category()'
Connection.o:/usr/include/boost/asio/error.hpp:220: more undefined references to`boost::system::system_category()' follow
Connection.o: In function `Connection::readFully(unsigned char*, int, boost::function<void (boost::system::error_code const&)>, boost::system::error_code)':
/home/madmantm/tortunnel/protocol/Connection.cpp:101: undefined reference to`SSL_read'
/home/madmantm/tortunnel/protocol/Connection.cpp:103: undefined reference to `SSL_get_error'
Connection.o: In function`error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to `boost::system::system_category()'
Connection.o: In function`Connection::initializeSSL()':
/home/madmantm/tortunnel/protocol/Connection.cpp:70: undefined reference to `SSL_set_connect_state'
Connection.o: In function`get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
/usr/include/boost/asio/error.hpp:220: undefined reference to`boost::system::system_category()'
Connection.o: In function `error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to`boost::system::system_category()'
/usr/include/boost/system/error_code.hpp:315: undefined reference to `boost::system::system_category()'
Connection.o: In function`get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
Connection.o:/usr/include/boost/asio/error.hpp:220: more undefined references to`boost::system::system_category()' follow
Connection.o: In function `__static_initialization_and_destruction_0':
/usr/include/boost/system/error_code.hpp:214: undefined reference to`boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:215: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:216: undefined reference to`boost::system::system_category()'
Connection.o: In function `get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to`boost::system::system_category()'
RelayCellDispatcher.o: In function `get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to`boost::system::system_category()'
RelayCellDispatcher.o: In function `error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to`boost::system::system_category()'
RelayCellDispatcher.o: In function `get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to`boost::system::system_category()'
RelayCellDispatcher.o:/usr/include/boost/system/error_code.hpp:315: more undefined references to `boost::system::system_category()' follow
RelayCellDispatcher.o: In function`__static_initialization_and_destruction_0':
/usr/include/boost/system/error_code.hpp:214: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:215: undefined reference to`boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:216: undefined reference to `boost::system::system_category()'
RelayCellDispatcher.o: In function`get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
ProxyShuffler.o: In function`__static_initialization_and_destruction_0':
/usr/include/boost/system/error_code.hpp:214: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:215: undefined reference to`boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:216: undefined reference to `boost::system::system_category()'
ProxyShuffler.o: In function`get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
TorTunnel.o: In function`error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to `boost::system::system_category()'
TorTunnel.o: In function`__static_initialization_and_destruction_0':
/usr/include/boost/system/error_code.hpp:214: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:215: undefined reference to`boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:216: undefined reference to `boost::system::system_category()'
TorTunnel.o: In function`get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
SocksConnection.o: In function`error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to `boost::system::system_category()'
SocksConnection.o: In function`get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
SocksConnection.o: In function`error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to `boost::system::system_category()'
SocksConnection.o:/usr/include/boost/system/error_code.hpp:315: more undefined references to`boost::system::system_category()' follow
SocksConnection.o: In function `__static_initialization_and_destruction_0':
/usr/include/boost/system/error_code.hpp:214: undefined reference to`boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:215: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:216: undefined reference to`boost::system::system_category()'
SocksConnection.o: In function `get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to`boost::system::system_category()'
HybridEncryption.o: In function `HybridEncryption::AES_encrypt(unsigned char*, int, unsigned char*, unsigned char*, int)':
/home/madmantm/tortunnel/protocol/HybridEncryption.cpp:59: undefined reference to`AES_set_encrypt_key'
/home/madmantm/tortunnel/protocol/HybridEncryption.cpp:60: undefined reference to `AES_ctr128_encrypt'
HybridEncryption.o: In function`HybridEncryption::encryptInHybridChunk(unsigned char_, int, unsigned char__, int_, rsa_st_)':
/home/madmantm/tortunnel/protocol/HybridEncryption.cpp:67: undefined reference to `RSA_size'
/home/madmantm/tortunnel/protocol/HybridEncryption.cpp:75: undefined reference to`RAND_bytes'
/home/madmantm/tortunnel/protocol/HybridEncryption.cpp:82: undefined reference to `RSA_public_encrypt'
HybridEncryption.o: In function`HybridEncryption::encryptInSingleChunk(unsigned char_, int, unsigned char**, int_, rsa_st_)':
/home/madmantm/tortunnel/protocol/HybridEncryption.cpp:94: undefined reference to `RSA_size'
HybridEncryption.o: In function`HybridEncryption::encrypt(unsigned char*, int, unsigned char**, int_, rsa_st_)':
/home/madmantm/tortunnel/protocol/HybridEncryption.cpp:104: undefined reference to `RSA_size'
HybridEncryption.o: In function`HybridEncryption::encryptInSingleChunk(unsigned char_, int, unsigned char__, int_, rsa_st_)':
/home/madmantm/tortunnel/protocol/HybridEncryption.cpp:97: undefined reference to `RSA_public_encrypt'
Directory.o: In function`__static_initialization_and_destruction_0':
/usr/include/boost/system/error_code.hpp:214: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:215: undefined reference to`boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:216: undefined reference to `boost::system::system_category()'
Directory.o: In function`get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
ServerListing.o: In function`ServerListing::getOnionKey()':
/home/madmantm/tortunnel/protocol/ServerListing.cpp:92: undefined reference to `RSA_new'
/home/madmantm/tortunnel/protocol/ServerListing.cpp:93: undefined reference to`BIO_new_mem_buf'
/home/madmantm/tortunnel/protocol/ServerListing.cpp:97: undefined reference to `PEM_read_bio_RSAPublicKey'
ServerListing.o: In function`__static_initialization_and_destruction_0':
/usr/include/boost/system/error_code.hpp:214: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:215: undefined reference to`boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:216: undefined reference to `boost::system::system_category()'
ServerListing.o: In function`get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
Util.o: In function`Util::getRandomId()':
/home/madmantm/tortunnel/util/Util.cpp:252: undefined reference to `RAND_bytes'
Util.o: In function`Util::getRandom()':
/home/madmantm/tortunnel/util/Util.cpp:259: undefined reference to `RAND_bytes'
Circuit.o: In function`Circuit::initializeDhParameters()':
/home/madmantm/tortunnel/protocol/Circuit.cpp:69: undefined reference to `BN_new'
/home/madmantm/tortunnel/protocol/Circuit.cpp:70: undefined reference to`BN_new'
/home/madmantm/tortunnel/protocol/Circuit.cpp:71: undefined reference to `DH_new'
/home/madmantm/tortunnel/protocol/Circuit.cpp:73: undefined reference to`BN_hex2bn'
/home/madmantm/tortunnel/protocol/Circuit.cpp:74: undefined reference to `BN_set_word'
/home/madmantm/tortunnel/protocol/Circuit.cpp:76: undefined reference to`BN_dup'
/home/madmantm/tortunnel/protocol/Circuit.cpp:77: undefined reference to `BN_dup'
Circuit.o: In function`~Circuit':
/home/madmantm/tortunnel/protocol/Circuit.cpp:280: undefined reference to `BN_free'
/home/madmantm/tortunnel/protocol/Circuit.cpp:281: undefined reference to`BN_free'
/home/madmantm/tortunnel/protocol/Circuit.cpp:282: undefined reference to `DH_free'
/home/madmantm/tortunnel/protocol/Circuit.cpp:283: undefined reference to`RSA_free'
Circuit.o: In function `get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to`boost::system::system_category()'
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
Circuit.o: In function`Circuit::initializeDhParameters()':
/home/madmantm/tortunnel/protocol/Circuit.cpp:79: undefined reference to `DH_generate_key'
Circuit.o: In function`__static_initialization_and_destruction_0':
/usr/include/boost/system/error_code.hpp:214: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:215: undefined reference to`boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:216: undefined reference to `boost::system::system_category()'
Circuit.o: In function`get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
CellEncrypter.o: In function`CellEncrypter':
/home/madmantm/tortunnel/protocol/CellEncrypter.cpp:50: undefined reference to `SHA1_Init'
CellEncrypter.o: In function`CellEncrypter::expandKeyMaterial(unsigned char_, int, unsigned char_, int)':
/home/madmantm/tortunnel/protocol/CellEncrypter.cpp:69: undefined reference to `SHA1'
CellEncrypter.o: In function`CellEncrypter::initKeyMaterial(unsigned char_)':
/home/madmantm/tortunnel/protocol/CellEncrypter.cpp:92: undefined reference to `SHA1_Update'
/home/madmantm/tortunnel/protocol/CellEncrypter.cpp:93: undefined reference to`SHA1_Update'
/home/madmantm/tortunnel/protocol/CellEncrypter.cpp:95: undefined reference to `AES_set_encrypt_key'
CellEncrypter.o: In function`CellEncrypter::aesOperate(Cell&, aes_key_st_, unsigned char_, unsigned char_, unsigned int_)':
/home/madmantm/tortunnel/protocol/CellEncrypter.cpp:124: undefined reference to `AES_ctr128_encrypt'
CellEncrypter.o: In function`CellEncrypter::calculateDigest(SHAstate_st_, RelayCell&, unsigned char_)':
/home/madmantm/tortunnel/protocol/CellEncrypter.cpp:132: undefined reference to `SHA1_Update'
/home/madmantm/tortunnel/protocol/CellEncrypter.cpp:137: undefined reference to`SHA1_Final'
CellEncrypter.o: In function `CellEncrypter':
/home/madmantm/tortunnel/protocol/CellEncrypter.cpp:51: undefined reference to`SHA1_Init'
CellEncrypter.o: In function `CellEncrypter::initKeyMaterial(unsigned char*)':
/home/madmantm/tortunnel/protocol/CellEncrypter.cpp:96: undefined reference to`AES_set_encrypt_key'
CellConsumer.o: In function `__static_initialization_and_destruction_0':
/usr/include/boost/system/error_code.hpp:214: undefined reference to`boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:215: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:216: undefined reference to`boost::system::system_category()'
CellConsumer.o: In function `get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to`boost::system::system_category()'
CreateCell.o: In function `CreateCell':
/home/madmantm/tortunnel/protocol/CreateCell.cpp:39: undefined reference to`BN_num_bits'
/home/madmantm/tortunnel/protocol/CreateCell.cpp:45: undefined reference to `BN_bn2bin'
Network.o: In function`error_code':
/usr/include/boost/system/error_code.hpp:315: undefined reference to `boost::system::system_category()'
/usr/include/boost/system/error_code.hpp:315: undefined reference to`boost::system::system_category()'
Network.o: In function `get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to`boost::system::system_category()'
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
/usr/include/boost/asio/error.hpp:220: undefined reference to`boost::system::system_category()'
Network.o:/usr/include/boost/system/error_code.hpp:315: more undefined references to `boost::system::system_category()' follow
Network.o: In function`__static_initialization_and_destruction_0':
/usr/include/boost/system/error_code.hpp:214: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:215: undefined reference to`boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:216: undefined reference to `boost::system::system_category()'
Network.o: In function`get_system_category':
/usr/include/boost/asio/error.hpp:220: undefined reference to `boost::system::system_category()'
CreatedCell.o: In function`CreatedCell::isValid()':
/home/madmantm/tortunnel/protocol/CreatedCell.cpp:45: undefined reference to `BN_num_bits'
CreatedCell.o: In function`CreatedCell::getKeyMaterial(unsigned char**, unsigned char**)':
/home/madmantm/tortunnel/protocol/CreatedCell.cpp:49: undefined reference to `BN_num_bits'
/home/madmantm/tortunnel/protocol/CreatedCell.cpp:49: undefined reference to`BN_bin2bn'
/home/madmantm/tortunnel/protocol/CreatedCell.cpp:50: undefined reference to `DH_size'
/home/madmantm/tortunnel/protocol/CreatedCell.cpp:51: undefined reference to`DH_compute_key'
/home/madmantm/tortunnel/protocol/CreatedCell.cpp:52: undefined reference to `BN_num_bits'
/home/madmantm/tortunnel/protocol/CreatedCell.cpp:54: undefined reference to`BN_free'
collect2: ld returned 1 exit status
make: **\* [torproxy] Error 1

**Comment by madmantm** [comment]
i installed all the required packages, was someone successful with ubuntu 11.10 x64?

**Comment by madmantm** [comment]
still doesn't work, i have tried again on a fresh system install.

any help is appreciated.

**Comment by jago25** [comment]
Perhaps a workaround would be to downgrade the libboost libraries by uninstalling them and then installing them all again from source? 

I will look into compiling on a VPS and copying the binary over to the Ubuntu system.

**Comment by scub** [comment]
There is a problem with the build system for the package, change your make file accordingly; autreconf, then ./configure && make

torproxy_LDFLAGS = -pthread
torproxy_LDADD = -lssl -lboost_system-mt -lcrypto

torscanner_LDFLAGS = -pthread
torscanner_LDADD = -lssl -lboost_system-mt -lcrypto

**Comment by madmantm** [comment]
Thanks it works now, on a 12.04 LTS X64 Ubuntu.

**Comment by st33l** [comment]
I have installed tortunnel successfully but get the error below. System - Ubuntu 12.04. Help is greatly appreciated. TIA.

ubuntu@ubuntu:~/tortunnel$ ./torproxy -n x.x.x.x
torproxy 0.3 by Moxie Marlinspike.
Retrieving directory listing...
Segmentation fault (core dumped)

**Comment by crackcomm** [comment]
@st33l have the same problem, I'm running BackTrack 5 RC 3.

```
torproxy 0.3 by Moxie Marlinspike.
Retrieving directory listing...
Added: x.x.x.x
(24 more...)
Added: x.x.x.x
Segmentation fault
```

**Comment by void-in** [comment]
Did anyone find a solution for this segmentation fault? I tested on BackTrack R2 32 bit and BackTrack R3 64 bit but every time the torproxy is run with either an exit node or through a random exit node, the Segmentation fault (core dump) error is returned. I would really appreciate any help

**Comment by manurautela** [comment]
I was able to resolve this issue and have commited it to my branch and requested for a pull request.
In the meantime if someone needs please use this change apart from the above mentioned makefile changes.

With these changes i was able to run tortunnel without any issue. (.torproxy -p 5060 -r)

<snip>
Choosing exit node at index: 1259 out of 1411 listings...
Connecting to exit node: 69.42.126.102:443
SSL Connection to node complete.  Setting up circuit.
Connected to Exit Node.  SOCKS proxy ready on 5060.
<snip>

https://github.com/manurautela/tortunnel/commit/60951bae79ecc5b15d78fb05b3d02dc7bd4a77f0

**Comment by technerd206** [comment]
@manurautela - your fix didn't fix it on my machine (x86_64)..

[ 1451.720481] torproxy[20056] general protection ip:7fc102249183 sp:7fffcc20cd90 error:0 in libstdc++.so.6.0.13[7fc1021a0000+f6000]

**Comment by void-in** [comment]
I can also confirm that it didn't work for me either. I am using BT 5 R3 x64. Followed your instruction and changed the Directory.h file and configure && make && make install but still getting segmentation fault.

**Comment by manurautela** [comment]
I tried it on Ubuntu 12.10 VM, the bug was more on logical part during the parsing of the directory server listing returned by (URL: http://128.31.0.34:9031/tor/status/all ) , rather than something else. 

Did you updated your make files as mentioned previously on this thread?

Apart from this i have another problem where it is unable to open stream via Exit Node. I am looking through that problem and if i find a solution will update also.

**Comment by ZxXxA** [comment]
Thanks Manurautela, tried it on Backtrack 5 R1/2/3 and Ubuntu 12.10 (all distributions installed on VMWare) )... I had many difficulties to compile, and when I could TorProxy never connected the outgoing server. I look forward an update to fix these errors. Thousands of blessings!

**Comment by sergiu1103** [comment]
Have you managed to get it working on BT5R3? The makefile and the Directory.h have been changed, torproxy re-compiled and installed but still the same issue.

**Comment by manurautela** [comment]
First of all apologies for not being able to follow up on this lately.

Regarding the BT5R3 and x64 issue. I managed to get it compiled there as well. Here is all that i did to get it work.

The compiling issue is primarily due to boost library and linker related settings on backtrack which comes by default on installing the boost library on backtrack.

I downloaded the latest backtrack image.

root@bt:/usr/lib# uname -a
Linux bt 3.2.6 #1 SMP Fri Feb 17 10:40:05 EST 2012 i686 GNU/Linux
sudo apt-get install libboost-system-dev

cd tortunnel
autoreconf
automake --add-missing
./configure <--- this sets the makefile to default settings !!! Modify the makefile after this step as mentioned previously and below as well.
make

I got a hint from this link :
http://stackoverflow.com/questions/3031768/boost-thread-linking-boost-thread-vs-boost-thread-mt

If you check libboost_thread_, there is no libboost_thread-mt_ but libboost_system-mt\* are present.

root@bt:/usr/lib# ls libboost*
libboost_filesystem.so.1.40.0   libboost_system-mt.so
libboost_python-py26.so.1.40.0  libboost_system.so
libboost_regex.so.1.40.0        libboost_system.so.1.40.0
libboost_system.a               libboost_thread.so.1.40.0
libboost_system-mt.a

same story in both folders: depending on you architecture.
/usr/lib and /usr/lib64

Solution (1)
don't use -lboost_thread only -pthread in the Makefile

torproxy_LDFLAGS = -pthread
torproxy_LDADD = -lssl -lboost_system-mt -lcrypto
torscanner_LDFLAGS = -pthread
torscanner_LDADD = -lssl -lboost_system-mt -lcrypto

Solution (2)
install the boost library using sources and install both version mt as well as normal(non-mt), so that libboost_thread-mt\* are installed. 
Pls check the documentation. http://www.boost.org/doc/libs/1_52_0/more/getting_started/unix-variants.html

torproxy_LDFLAGS = -lboost_thread-mt -pthread
torproxy_LDADD = -lssl -lboost_system-mt -lcrypto
torscanner_LDFLAGS = -lboost_thread-mt -pthread
torscanner_LDADD = -lssl -lboost_system-mt -lcrypto

Finally: 
torproxy 0.3 by Moxie Marlinspike.
Retrieving directory listing...
...
Added: 213.251.185.74
Added: 97.85.163.142
Added: 66.209.35.140
Added: 74.120.12.135
Added: 198.98.49.3
Added: 50.55.177.218
Choosing exit node at index: 1324 out of 1428 listings...
Connecting to exit node: 109.169.33.163:443
SSL Connection to node complete.  Setting up circuit.
Connected to Exit Node.  SOCKS proxy ready on 5060.

In case you want to see which IP Addresses get added.
Uncomment this line in Directory.cpp
void Directory::retrieveDirectoryListingComplete(...)
{
<....>
std::cerr << "Added: " << exitNode->getAddress() << std::endl;
<...>
}

I have also updated Directory.h file that i am using with very basic related to previous fix only. Might wanna pick that if interested.

But the issue related to Opening stream still needs to be investigated.

Hope it helps.

**Comment by ZxXxA** [comment]
It worked. In Backtrack 5 R3 is perfect, I installed it from the repository gitCLone /manurautela/tortunnel. Thanks for sharing solutions and spend some of their time. Greetings!

root@bt:~# torproxy -r -p 5060
torproxy 0.3 by Moxie Marlinspike.
Retrieving directory listing...
Choosing exit node at index: 623 out of 1411 listings...
Connecting to exit node: 66.25.183.116:9001
SSL Connection to node complete.  Setting up circuit.
Connected to Exit Node.  SOCKS proxy ready on 5060.

JAHBLessed!

**Comment by dankvz** [comment]
guys i need help... ive tried all mentioned above. Patched Makefile. Tried making changes to Directory.h. Had sources from git/moxie, and from  /manurautela/tortunnel, and original v 0.3 from thoughtcrime. Tried with boost versions 1.53, then downgraded to 1.49.
when it compiles with no errors, it gives me Floating Point exception.

Im on Kali Debian linux... Thanks a lot for all your efforts to present point, and for your help :)

**Comment by ghost** [comment]
Same problem as @dankvz  ... i get a "Floating Point exception" in every case (fresh installs of BTR5, using apt to get boost, installing boost manually...everything).

Any ideas anyone?

**Comment by crackcomm** [comment]
Im not sure but it may be a directory listings protocol incompatibility.

**Comment by ghost** [comment]
@manurautela are you still around to help out?

**Comment by ghost** [comment]
@crackcomm can u give me some steps to try out your hypothesis?

**Comment by crackcomm** [comment]
When i built @manurautela solution it still wasn't working on some directory listings.

**Comment by ghost** [comment]
@crackcomm does this mean u did get it working in other directory listings?  Please explain in more detail please.

**Comment by crackcomm** [comment]
Yes. It was some time ago, but if u would try many different listings there is a chance that some of them will work.

**Comment by ghost** [comment]
Although a long time ago are there any listings in particular that you may recall that stood out? (to save me a few hours of random checking)

**Comment by crackcomm** [comment]
No, im sorry, but i would suggest to write bash/python/whatever 10 lines script to do this job, it will probably save u more time.

**Comment by hackabit** [comment]
DAMN Floating point exception - on bt5 r3 32 bit
installed tortunnel via github. using apt-get installed the following packages:
libboost-dev                    install
libboost-filesystem1.40.0           install
libboost-python1.40.0               install
libboost-regex1.40.0                install
libboost-system-dev             install
libboost-system1.40-dev             install
libboost-system1.40.0               install
libboost-thread1.40.0               install
libboost1.40-dev                install

make went well but when running torproxy -p 5060 - r     I get the following:
torproxy 0.3 by Moxie Marlinspike.
Retrieving directory listing...
Floating point exception

if I enter instead : torproxy -p 5060  -n 199.48.147.41 (where I explicity give a Tor exit node ip) I get:
 torproxy 0.3 by Moxie Marlinspike.
Retrieving directory listing...
terminate called after throwing an instance of 'ServerNotFoundException'
  what():  Specified server not found in directory...
Aborted

Any1 ideas ? I read above about different directory listings, How & Where can I change them???

**Comment by ghost** [comment]
Yup, IDENTICAL problem as you.  I was the guy who posted above.  The directory listing thing didnt help.  I cant figure out what is going on.  I gave up.  I even tried older BackTrack releases, older Ubuntus, etc.  All the same problems.  Can't figure it out.  

If you learn anything new please share.

**Comment by scub** [comment]
The functionality within the protocol that tortunnel uses to construct its single hop circuits has been removed, as it is seen as an abuse of the protocol. Even after a successful patching, any attempts to connect will quickly throw an "Error opening stream: system:111" and refuse any connections.  It will definitely take a bit of out of the box thinking to breath life back into this hellion.

Related Materials
https://trac.torproject.org/projects/tor/ticket/1751
https://blog.torproject.org/blog/tor-02232-released
- Major features (relays control their load better):
  
  Exit relays now try harder to block exit attempts from unknown
  relays, to make it harder for people to use them as one-hop proxies
  a la tortunnel. Controlled by the refuseunknownexits consensus
  parameter (currently enabled), or you can override it on your
  relay with the RefuseUnknownExits torrc option. Resolves bug 1751;
  based on a variant of proposal 163.

**Comment by hackabit** [comment]
Regarding the above what r u saying Scub is that tortunnel by Moxie has broken totally due to new restrictions in the protocol?
I am having the Floating point exception and I don't know if it is related... this exception rises in the protocol/Directory.cpp file as the serverListing.size() is Zero , looks like the retrieveDirectoryListing function in the same file didn't bring any listing of exit nodes via the GET /tor/status/all HTTP/1.0 web service call  to 128.31.0.34 port 9031. Can any1 confirm this? maybe we just need to find another web service to get Tor exit nodes with the same format which I guess is HTML? Can this fix the problem?

**Comment by justingoldberg** [comment]
Here's the commands to get this working on a 32-bit machine (kali linux 1.0.6 fresh install [kali is debian-based] on a dell inspiron e1505 [6400])

install automake:
apt-get install automake
install libboost:
apt-get install libboost-system-dev

compile and install torproxy:
git clone https://github.com/manurautela/tortunnel
cd tortunnel
autoreconf
automake --add-missing
./configure
make
make install

Is there a way to use tortunnel, in a way that doesn't abuse the tor network (eg not use a one-hop relay)?

Has anyone thought about porting tortilla to linux?
https://github.com/CrowdStrike/Tortilla

**Comment by adrianabadin** [comment]
i cant compile tortunnel when i run autoreconf it send me the following error
configure.ac:2: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.ac:2: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
Makefile.am:6: warning: source file 'protocol/HybridEncryption.cpp' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
Makefile.am:6: warning: source file 'protocol/Connection.cpp' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
Makefile.am:6: warning: source file 'protocol/Cell.cpp' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
Makefile.am:6: warning: source file 'protocol/Directory.cpp' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
Makefile.am:6: warning: source file 'protocol/ServerListing.cpp' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
Makefile.am:6: warning: source file 'util/Util.cpp' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
Makefile.am:6: warning: source file 'protocol/Circuit.cpp' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
Makefile.am:6: warning: source file 'protocol/CellEncrypter.cpp' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
Makefile.am:6: warning: source file 'protocol/RelayCellDispatcher.cpp' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
Makefile.am:6: warning: source file 'protocol/CellConsumer.cpp' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
Makefile.am:6: warning: source file 'protocol/CreateCell.cpp' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
Makefile.am:6: warning: source file 'protocol/CreatedCell.cpp' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
Makefile.am:6: warning: source file 'util/Network.cpp' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
Makefile.am:11: warning: source file 'protocol/HybridEncryption.cpp' is in a subdirectory,
Makefile.am:11: but option 'subdir-objects' is disabled
Makefile.am:11: warning: source file 'protocol/Connection.cpp' is in a subdirectory,
Makefile.am:11: but option 'subdir-objects' is disabled
Makefile.am:11: warning: source file 'protocol/Cell.cpp' is in a subdirectory,
Makefile.am:11: but option 'subdir-objects' is disabled
Makefile.am:11: warning: source file 'protocol/Directory.cpp' is in a subdirectory,
Makefile.am:11: but option 'subdir-objects' is disabled
Makefile.am:11: warning: source file 'protocol/ServerListing.cpp' is in a subdirectory,
Makefile.am:11: but option 'subdir-objects' is disabled
Makefile.am:11: warning: source file 'util/Util.cpp' is in a subdirectory,
Makefile.am:11: but option 'subdir-objects' is disabled
Makefile.am:11: warning: source file 'protocol/Circuit.cpp' is in a subdirectory,
Makefile.am:11: but option 'subdir-objects' is disabled
Makefile.am:11: warning: source file 'protocol/CellEncrypter.cpp' is in a subdirectory,
Makefile.am:11: but option 'subdir-objects' is disabled
Makefile.am:11: warning: source file 'protocol/RelayCellDispatcher.cpp' is in a subdirectory,
Makefile.am:11: but option 'subdir-objects' is disabled
Makefile.am:11: warning: source file 'protocol/CellConsumer.cpp' is in a subdirectory,
Makefile.am:11: but option 'subdir-objects' is disabled
Makefile.am:11: warning: source file 'protocol/CreateCell.cpp' is in a subdirectory,
Makefile.am:11: but option 'subdir-objects' is disabled
Makefile.am:11: warning: source file 'protocol/CreatedCell.cpp' is in a subdirectory,
Makefile.am:11: but option 'subdir-objects' is disabled
Makefile.am:11: warning: source file 'util/Network.cpp' is in a subdirectory,
Makefile.am:11: but option 'subdir-objects' is disabled
Makefile.am:11: warning: source file 'protocol/ServerListingGroup.cpp' is in a subdirectory,
Makefile.am:11: but option 'subdir-objects' is disabled
and then when i try to do automake and make it says reference to placeholders seems ambiguos
